using CKEditor.Demo.Server.Model;

namespace CKEditor.Demo.Server.Services;

/// <summary>
/// Primitive in-memory image store for the upload demo.
/// Each stored image is keyed by a randomly generated ID and can be retrieved
/// via the <c>GET /api/images/{id}</c> endpoint registered in <c>Program.cs</c>.
/// </summary>
public sealed class ImageStorageService
{
    private readonly Dictionary<string, StoredImage> _images = new(StringComparer.Ordinal);
    private readonly object _lock = new();

    /// <summary>Stores raw image bytes and returns their public path.</summary>
    /// <param name="fileName">Original file name (used as a download hint in the response).</param>
    /// <param name="mimeType">MIME type, e.g. <c>image/jpeg</c>.</param>
    /// <param name="data">Raw binary content.</param>
    /// <returns>A relative URL of the form <c>/api/images/{id}</c>.</returns>
    public string Store(string fileName, string mimeType, byte[] data)
    {
        var id = Guid.NewGuid().ToString("N");

        lock (_lock)
        {
            _images[id] = new StoredImage(fileName, mimeType, data);
        }

        return $"/api/images/{id}";
    }

    /// <summary>Retrieves a stored image by its ID, or <see langword="null"/> if not found.</summary>
    /// <param name="id">The image ID, as generated by <see cref="Store"/>.</param>
    /// <returns>The stored image, or <see langword="null"/> if not found.</returns>
    public StoredImage? Get(string id)
    {
        lock (_lock)
        {
            return _images.TryGetValue(id, out var img) ? img : null;
        }
    }

    /// <summary>Returns all stored images with their IDs (newest last).</summary>
    /// <returns>A list of tuples containing image IDs and their corresponding stored images.</returns>
    public IReadOnlyList<(string Id, StoredImage Image)> GetAll()
    {
        lock (_lock)
        {
            return _images.Select(kv => (kv.Key, kv.Value)).ToList();
        }
    }
}
